const data = [
  {
    _id: "62f14209918decd4d6a86d5f",
    index: 0,
    guid: "953ca075-fcee-44d9-ad29-022fb1376775",
    isActive: false,
    balance: "$2,253.84",
    picture: "http://placehold.it/32x32",
    age: 35,
    eyeColor: "green",
    name: "Bonner Bailey",
    gender: "male",
    company: "CUBICIDE",
    email: "bonnerbailey@cubicide.com",
    phone: "+1 (818) 499-2187",
    address: "831 Fuller Place, Lowell, Wisconsin, 3552",
    about:
      "Fugiat velit eiusmod aliquip do culpa proident excepteur incididunt sint. Et consequat sint ipsum culpa cillum elit reprehenderit ad ex. Mollit occaecat cillum labore reprehenderit aliqua pariatur in elit dolor cupidatat voluptate deserunt proident. Excepteur do voluptate proident tempor excepteur ad cupidatat culpa eu nostrud laborum. Occaecat velit elit minim esse ex qui reprehenderit ullamco incididunt deserunt exercitation. Et ipsum exercitation amet proident ullamco pariatur ea duis nulla occaecat enim nisi.\r\n",
    registered: "2021-07-16T03:05:57 -06:-30",
    latitude: -44.166219,
    longitude: -135.938743,
    tags: ["tempor", "enim", "amet", "sint", "consequat", "anim", "magna"],
    friends: [
      {
        id: 0,
        name: "Hoffman Vega",
      },
      {
        id: 1,
        name: "Jewell Schwartz",
      },
      {
        id: 2,
        name: "Livingston Pittman",
      },
    ],
    greeting: "Hello, Bonner Bailey! You have 6 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "62f1420921ac44b001e52755",
    index: 1,
    guid: "b72a1264-4b1e-4af4-98b7-708efa3c862e",
    isActive: true,
    balance: "$1,207.40",
    picture: "http://placehold.it/32x32",
    age: 31,
    eyeColor: "blue",
    name: "Shepard Chapman",
    gender: "male",
    company: "LEXICONDO",
    email: "shepardchapman@lexicondo.com",
    phone: "+1 (850) 509-3643",
    address: "582 Karweg Place, Imperial, Utah, 387",
    about:
      "Exercitation do anim occaecat tempor. Aliqua est amet nostrud labore. Ut magna velit esse nulla magna ipsum ex excepteur ea exercitation cupidatat.\r\n",
    registered: "2015-06-05T03:36:20 -06:-30",
    latitude: -63.187691,
    longitude: -129.334096,
    tags: ["est", "culpa", "ut", "dolor", "anim", "adipisicing", "esse"],
    friends: [
      {
        id: 0,
        name: "Adkins Garrett",
      },
      {
        id: 1,
        name: "Francine Fuller",
      },
      {
        id: 2,
        name: "Angeline Boyle",
      },
    ],
    greeting: "Hello, Shepard Chapman! You have 5 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "62f14209e759306f02d2bf85",
    index: 2,
    guid: "29982701-e83d-4ed9-bc8c-d1ae05b730c2",
    isActive: false,
    balance: "$3,095.45",
    picture: "http://placehold.it/32x32",
    age: 37,
    eyeColor: "blue",
    name: "Coleen Bruce",
    gender: "female",
    company: "MAGMINA",
    email: "coleenbruce@magmina.com",
    phone: "+1 (977) 473-3442",
    address: "514 Albee Square, Faxon, Indiana, 6373",
    about:
      "Deserunt ex commodo dolor eu officia qui amet ad. Eiusmod sint minim ullamco incididunt esse cillum labore non tempor fugiat mollit Lorem sunt. Esse quis sit fugiat dolor laborum irure ullamco anim consectetur qui tempor deserunt. Do et id elit laborum ut cupidatat et laborum elit excepteur aliquip. Aliquip anim non duis et laborum anim voluptate pariatur aute ipsum. Duis ipsum elit sit reprehenderit velit ipsum voluptate eiusmod commodo commodo nisi. Cupidatat enim incididunt officia consequat.\r\n",
    registered: "2014-04-10T06:09:15 -06:-30",
    latitude: 19.749335,
    longitude: 50.044236,
    tags: ["Lorem", "laborum", "excepteur", "pariatur", "eu", "aute", "ea"],
    friends: [
      {
        id: 0,
        name: "Lauri Maldonado",
      },
      {
        id: 1,
        name: "Pearson Salazar",
      },
      {
        id: 2,
        name: "Elinor Richards",
      },
    ],
    greeting: "Hello, Coleen Bruce! You have 1 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "62f1420991889dc430a7e278",
    index: 3,
    guid: "6c51b2d0-b67d-4d90-a2a5-f9ee5498af91",
    isActive: false,
    balance: "$2,868.74",
    picture: "http://placehold.it/32x32",
    age: 39,
    eyeColor: "blue",
    name: "Wiley Garcia",
    gender: "male",
    company: "ZAGGLE",
    email: "wileygarcia@zaggle.com",
    phone: "+1 (908) 535-2062",
    address: "323 Tehama Street, Goochland, Pennsylvania, 8864",
    about:
      "Occaecat culpa eu anim veniam ad in commodo in fugiat cillum occaecat deserunt dolor minim. Quis enim aliquip exercitation occaecat in reprehenderit anim duis sit ad officia eu minim velit. Labore anim sunt adipisicing minim qui dolor laboris veniam id tempor aute sunt id. Exercitation veniam amet sunt officia ad sit deserunt deserunt adipisicing aute minim quis cillum labore. Voluptate culpa sit pariatur deserunt id do quis quis ad nisi sint duis anim.\r\n",
    registered: "2016-10-19T12:50:10 -06:-30",
    latitude: -75.827731,
    longitude: -9.629335,
    tags: [
      "pariatur",
      "proident",
      "dolore",
      "sit",
      "occaecat",
      "reprehenderit",
      "enim",
    ],
    friends: [
      {
        id: 0,
        name: "Naomi Hawkins",
      },
      {
        id: 1,
        name: "Mcconnell Conner",
      },
      {
        id: 2,
        name: "Kerry Terrell",
      },
    ],
    greeting: "Hello, Wiley Garcia! You have 5 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "62f142098df89c5f57ee7d20",
    index: 4,
    guid: "93d76142-39bf-4725-b96c-d4cb5db132d6",
    isActive: true,
    balance: "$1,409.90",
    picture: "http://placehold.it/32x32",
    age: 28,
    eyeColor: "blue",
    name: "Lindsey Lang",
    gender: "female",
    company: "JAMNATION",
    email: "lindseylang@jamnation.com",
    phone: "+1 (895) 558-2581",
    address: "835 Miami Court, Riegelwood, New Hampshire, 4376",
    about:
      "Velit excepteur voluptate consequat sunt Lorem sit Lorem non quis fugiat eiusmod. Tempor id ut quis occaecat ea irure adipisicing proident enim. Dolore adipisicing duis laboris dolore incididunt id laborum magna ullamco occaecat consectetur dolor. Nostrud officia est magna et amet enim ipsum enim laboris voluptate. Labore magna ad sit officia consectetur Lorem consectetur sunt.\r\n",
    registered: "2021-10-01T11:04:28 -06:-30",
    latitude: 32.77354,
    longitude: -154.837003,
    tags: [
      "officia",
      "nisi",
      "officia",
      "laboris",
      "anim",
      "mollit",
      "laboris",
    ],
    friends: [
      {
        id: 0,
        name: "Hayden Sawyer",
      },
      {
        id: 1,
        name: "Nellie Mckay",
      },
      {
        id: 2,
        name: "Lindsay Small",
      },
    ],
    greeting: "Hello, Lindsey Lang! You have 5 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "62f14209aaba5a705748788e",
    index: 5,
    guid: "f3badfe5-a4c9-474b-9012-6351c2d97bd1",
    isActive: false,
    balance: "$2,379.40",
    picture: "http://placehold.it/32x32",
    age: 21,
    eyeColor: "green",
    name: "Rush Bray",
    gender: "male",
    company: "QUAILCOM",
    email: "rushbray@quailcom.com",
    phone: "+1 (966) 470-2130",
    address: "733 Danforth Street, Campo, District Of Columbia, 3024",
    about:
      "Nostrud enim fugiat velit sint dolore tempor qui in dolore qui amet eu eu eiusmod. Irure deserunt voluptate est deserunt culpa reprehenderit incididunt culpa veniam commodo laborum. Ipsum exercitation labore deserunt non. Incididunt pariatur reprehenderit ut exercitation ipsum amet. Tempor cillum qui qui qui consequat mollit. Nostrud incididunt Lorem tempor in nisi enim incididunt. Cupidatat excepteur consequat nostrud esse Lorem.\r\n",
    registered: "2016-08-31T04:25:26 -06:-30",
    latitude: -82.383238,
    longitude: -71.835865,
    tags: ["laborum", "sint", "quis", "est", "aliquip", "enim", "elit"],
    friends: [
      {
        id: 0,
        name: "Thornton Dyer",
      },
      {
        id: 1,
        name: "Fitzgerald Moore",
      },
      {
        id: 2,
        name: "Larson Fleming",
      },
    ],
    greeting: "Hello, Rush Bray! You have 7 unread messages.",
    favoriteFruit: "strawberry",
  },
];
module.exports = data;
